;;; org-link-beautify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-link-beautify-new.el

(autoload 'org-link-beautify-enable "org-link-beautify-new" "\
Enable `org-link-beautify'.")
(autoload 'org-link-beautify-disable "org-link-beautify-new" "\
Disable `org-link-beautify'.")
(defvar org-link-beautify-mode nil "\
Non-nil if Org-Link-Beautify mode is enabled.
See the `org-link-beautify-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `org-link-beautify-mode'.")
(custom-autoload 'org-link-beautify-mode "org-link-beautify-new" nil)
(autoload 'org-link-beautify-mode "org-link-beautify-new" "\
A minor mode to beautify Org Mode links with icons, and inline preview etc.

This is a global minor mode.  If called interactively, toggle the
`Org-Link-Beautify mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='org-link-beautify-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-link-beautify-new" '("org-link-beautify-"))


;;; Generated autoloads from org-link-beautify-old.el

(autoload 'org-link-beautify-enable "org-link-beautify-old" "\
Enable `org-link-beautify'.")
(autoload 'org-link-beautify-disable "org-link-beautify-old" "\
Disable `org-link-beautify'.")
(autoload 'org-link-beautify-mode "org-link-beautify-old" "\
A minor mode to beautify Org Mode links with icons, and inline preview etc.

This is a minor mode.  If called interactively, toggle the
`Org-Link-Beautify mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `org-link-beautify-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "org-link-beautify-old" '("org-link-beautify-"))

;;; End of scraped data

(provide 'org-link-beautify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-link-beautify-autoloads.el ends here
